# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import image_classification_1_pb2 as image__classification__1__pb2


class BrickStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.process = channel.unary_unary(
            '/Brick/process',
            request_serializer=image__classification__1__pb2.Images.SerializeToString,
            response_deserializer=image__classification__1__pb2.ImageClassificationResults.FromString,
        )


class BrickServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def process(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrickServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'process': grpc.unary_unary_rpc_method_handler(
            servicer.process,
            request_deserializer=image__classification__1__pb2.Images.FromString,
            response_serializer=image__classification__1__pb2.ImageClassificationResults.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Brick', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
