# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification_1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='image_classification_1.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x1cimage_classification_1.proto\"\x7f\n\x05Image\x12\x0f\n\x07imageID\x18\x01 \x01(\x05\x12\x12\n\nimageBytes\x18\x02 \x01(\x0c\x12\x12\n\nimageWidth\x18\x03 \x01(\x05\x12\x13\n\x0bimageHeight\x18\x04 \x01(\x05\x12\x18\n\x10numberOfChannels\x18\x05 \x01(\x05\x12\x0e\n\x06sentAt\x18\x06 \x01(\x02\"0\n\x06Images\x12\x16\n\x06images\x18\x01 \x03(\x0b\x32\x06.Image\x12\x0e\n\x06sentAt\x18\x06 \x01(\x02\"e\n\x19ImageClassificationResult\x12\x15\n\x05image\x18\x01 \x01(\x0b\x32\x06.Image\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0e\n\x06sentAt\x18\x06 \x01(\x02\"l\n\x1aImageClassificationResults\x12>\n\x1aimageClassificationResults\x18\x01 \x03(\x0b\x32\x1a.ImageClassificationResult\x12\x0e\n\x06sentAt\x18\x06 \x01(\x02\x32:\n\x05\x42rick\x12\x31\n\x07process\x12\x07.Images\x1a\x1b.ImageClassificationResults\"\x00\x62\x06proto3'
)

_IMAGE = _descriptor.Descriptor(
    name='Image',
    full_name='Image',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='imageID', full_name='Image.imageID', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='imageBytes', full_name='Image.imageBytes', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='imageWidth', full_name='Image.imageWidth', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='imageHeight', full_name='Image.imageHeight', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='numberOfChannels', full_name='Image.numberOfChannels', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sentAt', full_name='Image.sentAt', index=5,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=159,
)

_IMAGES = _descriptor.Descriptor(
    name='Images',
    full_name='Images',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='images', full_name='Images.images', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sentAt', full_name='Images.sentAt', index=1,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=161,
    serialized_end=209,
)

_IMAGECLASSIFICATIONRESULT = _descriptor.Descriptor(
    name='ImageClassificationResult',
    full_name='ImageClassificationResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='image', full_name='ImageClassificationResult.image', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='label', full_name='ImageClassificationResult.label', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='confidence', full_name='ImageClassificationResult.confidence', index=2,
            number=3, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sentAt', full_name='ImageClassificationResult.sentAt', index=3,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=211,
    serialized_end=312,
)

_IMAGECLASSIFICATIONRESULTS = _descriptor.Descriptor(
    name='ImageClassificationResults',
    full_name='ImageClassificationResults',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='imageClassificationResults', full_name='ImageClassificationResults.imageClassificationResults',
            index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sentAt', full_name='ImageClassificationResults.sentAt', index=1,
            number=6, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=314,
    serialized_end=422,
)

_IMAGES.fields_by_name['images'].message_type = _IMAGE
_IMAGECLASSIFICATIONRESULT.fields_by_name['image'].message_type = _IMAGE
_IMAGECLASSIFICATIONRESULTS.fields_by_name['imageClassificationResults'].message_type = _IMAGECLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Images'] = _IMAGES
DESCRIPTOR.message_types_by_name['ImageClassificationResult'] = _IMAGECLASSIFICATIONRESULT
DESCRIPTOR.message_types_by_name['ImageClassificationResults'] = _IMAGECLASSIFICATIONRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
    'DESCRIPTOR': _IMAGE,
    '__module__': 'image_classification_1_pb2'
    # @@protoc_insertion_point(class_scope:Image)
})
_sym_db.RegisterMessage(Image)

Images = _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
    'DESCRIPTOR': _IMAGES,
    '__module__': 'image_classification_1_pb2'
    # @@protoc_insertion_point(class_scope:Images)
})
_sym_db.RegisterMessage(Images)

ImageClassificationResult = _reflection.GeneratedProtocolMessageType('ImageClassificationResult', (_message.Message,), {
    'DESCRIPTOR': _IMAGECLASSIFICATIONRESULT,
    '__module__': 'image_classification_1_pb2'
    # @@protoc_insertion_point(class_scope:ImageClassificationResult)
})
_sym_db.RegisterMessage(ImageClassificationResult)

ImageClassificationResults = _reflection.GeneratedProtocolMessageType('ImageClassificationResults', (_message.Message,),
                                                                      {
                                                                          'DESCRIPTOR': _IMAGECLASSIFICATIONRESULTS,
                                                                          '__module__': 'image_classification_1_pb2'
                                                                          # @@protoc_insertion_point(class_scope:ImageClassificationResults)
                                                                      })
_sym_db.RegisterMessage(ImageClassificationResults)

_BRICK = _descriptor.ServiceDescriptor(
    name='Brick',
    full_name='Brick',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=424,
    serialized_end=482,
    methods=[
        _descriptor.MethodDescriptor(
            name='process',
            full_name='Brick.process',
            index=0,
            containing_service=None,
            input_type=_IMAGES,
            output_type=_IMAGECLASSIFICATIONRESULTS,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_BRICK)

DESCRIPTOR.services_by_name['Brick'] = _BRICK

# @@protoc_insertion_point(module_scope)
